import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">HackathonbeautyOne</Link>
        </li>
        <li>
          <Link to="/sitemap1version">Sitemap1version</Link>
        </li>
        <li>
          <Link to="/buttonsone">ButtonsOne</Link>
        </li>
        <li>
          <Link to="/sitemap2version">Sitemap2version</Link>
        </li>
        <li>
          <Link to="/sitemap2versionone">Sitemap2versionOne</Link>
        </li>
        <li>
          <Link to="/componentstwo">ComponentsTwo</Link>
        </li>
        <li>
          <Link to="/components">Components</Link>
        </li>
        <li>
          <Link to="/buttons">Buttons</Link>
        </li>
        <li>
          <Link to="/productcardthree">ProductcardThree</Link>
        </li>
        <li>
          <Link to="/signin">Signin</Link>
        </li>
        <li>
          <Link to="/signup">Signup</Link>
        </li>
        <li>
          <Link to="/checkout">Checkout</Link>
        </li>
        <li>
          <Link to="/info">Info</Link>
        </li>
        <li>
          <Link to="/lipslipstick">LipsLipstick</Link>
        </li>
        <li>
          <Link to="/productcardtwo">ProductcardTwo</Link>
        </li>
        <li>
          <Link to="/productcard">Productcard</Link>
        </li>
        <li>
          <Link to="/cataloglips">CatalogLips</Link>
        </li>
        <li>
          <Link to="/wwwultacombyhtmltodesignfreeversion09032023">
            WwwultacombyhtmltodesignFREEversion09032023
          </Link>
        </li>
        <li>
          <Link to="/cart">Cart</Link>
        </li>
        <li>
          <Link to="/wwwultacombyhtmltodesignfreeversion09032023two">
            WwwultacombyhtmltodesignFREEversion09032023Two
          </Link>
        </li>
        <li>
          <Link to="/wwwultacombyhtmltodesignfreeversion09032023one">
            WwwultacombyhtmltodesignFREEversion09032023One
          </Link>
        </li>
        <li>
          <Link to="/productcardone">ProductcardOne</Link>
        </li>
        <li>
          <Link to="/buttonstwo">ButtonsTwo</Link>
        </li>
        <li>
          <Link to="/componentsone">ComponentsOne</Link>
        </li>
        <li>
          <Link to="/hackathonbeauty">Hackathonbeauty</Link>
        </li>
        <li>
          <Link to="/hackathonbeautytwo">HackathonbeautyTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
